
#    dynamic:
#      p6spy: false
#      hikari:
#        catalog:
#        connection-timeout: 6000
#        idle-timeout: 60000
#        max-pool-size: 10
#        min-idle: 3
#        connection-test-query: select 1 from dual
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: root
#        other:
#          url: jdbc:mysql://localhost:3306/tp_music_other?serverTimezone=Asia/Shanghai
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: root
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  resources:
      static-locations: classpath:/static/,classpath:/resources/
  thymeleaf:
    prefix: classpath:/static/

  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      custom:
        database: music-web
        host:
            - 127.0.0.1
            - 127.0.0.1
            - 127.0.0.1
            - 127.0.0.1
        port:
            - 27020
            - 27021
            - 27022
            - 27023
        username: user
        password: user
        maxConnections: 100
        minConnections: 10







#server:
#  port: 8090
#  servlet: web-music
logging:
  level:
    root: info
    org.springframework.data.mongodb.core: error
