

spring:
  application:
    name: music-websits # 应用名称
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    additional-paths: src/main/java
    exclude: WEB-INF/**
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.yin.entity


server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 100
    min-spare-threads: 30