
#    dynamic:
#      p6spy: false
#      hikari:
#        catalog:
#        connection-timeout: 6000
#        idle-timeout: 60000
#        max-pool-size: 10
#        min-idle: 3
#        connection-test-query: select 1 from dual
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: root
#        other:
#          url: jdbc:mysql://localhost:3306/tp_music_other?serverTimezone=Asia/Shanghai
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: root
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
      static-locations: classpath:/static/,classpath:/resources/
  thymeleaf:
    prefix: classpath:/static/

  devtools:
    restart:
      enabled: true
server:
  port: 8090
  servlet: web-music

